# Statistics

In [1]:
import numpy as np
import pandas as pd

## Mean, Median, Variance and Standard Deviation

### Mean - O(n)

In [2]:
a = np.array([3, 6, 2,8,5])
np.mean(a)

4.8

In [3]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.mean(a)

5.0

In [4]:
np.mean(a, axis=0) #column-wise

array([4., 5., 6.])

In [5]:
np.mean(a, axis=1)

array([2., 5., 8.])

In [7]:
df = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]])
df.mean() #df.mean(axis=0)

0    4.0
1    5.0
2    6.0
dtype: float64

In [8]:
df.mean(axis=1)

0    2.0
1    5.0
2    8.0
dtype: float64

### Median - O(n logn)
Value in the middle of the ascending ordered array:
- Odd: Element in the middle
- Even: Average of the two elements in the middle

#### Numpy

In [10]:
a = np.array([[1,5,9,4],[3,8,4,7], [4,9,3,8]])

In [11]:
np.median(a)

4.5

In [12]:
np.median(a, axis=0)

array([3., 8., 4., 7.])

In [13]:
np.median(a, axis=1)

array([4.5, 5.5, 6. ])

#### Pandas

In [14]:
df = pd.DataFrame([[1,5,9,4],[3,8,4,7], [4,9,3,8]])

In [15]:
df.median() #=axis=0

0    3.0
1    8.0
2    4.0
3    7.0
dtype: float64

In [16]:
df.median(axis=1)

0    4.5
1    5.5
2    6.0
dtype: float64

### Mode
Most repetitive value in a data set.