# Statistics

In [21]:
import numpy as np
import pandas as pd
import statistics
import scipy

## Measures of Central Tendency (Mean, Median and Mode)

### Mean - O(n)

In [2]:
a = np.array([3, 6, 2,8,5])
np.mean(a)

4.8

In [3]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.mean(a)

5.0

In [4]:
np.mean(a, axis=0) #column-wise

array([4., 5., 6.])

In [5]:
np.mean(a, axis=1)

array([2., 5., 8.])

In [6]:
df = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]])
df.mean() #df.mean(axis=0)

0    4.0
1    5.0
2    6.0
dtype: float64

In [7]:
df.mean(axis=1)

0    2.0
1    5.0
2    8.0
dtype: float64

### Median - O(n logn)
Value in the middle of the ascending ordered array:
- Odd: Element in the middle
- Even: Average of the two elements in the middle

#### Numpy

In [8]:
a = np.array([[1,5,9,4],[3,8,4,7], [4,9,3,8]])

In [9]:
np.median(a)

4.5

In [10]:
np.median(a, axis=0)

array([3., 8., 4., 7.])

In [11]:
np.median(a, axis=1)

array([4.5, 5.5, 6. ])

#### Pandas

In [12]:
df = pd.DataFrame([[1,5,9,4],[3,8,4,7], [4,9,3,8]])

In [13]:
df.median() #=axis=0

0    3.0
1    8.0
2    4.0
3    7.0
dtype: float64

In [14]:
df.median(axis=1)

0    4.5
1    5.5
2    6.0
dtype: float64

### Mode
Most repetitive value in a data set.

In [15]:
a = [3, 5, 7, 3, 8, 150, 4, 7,  1, 7]

In [18]:
statistics.mode(a)

7

In [19]:
a = [1, 2, 2, 1, 3, 3, 6, 8, 6]

In [20]:
statistics.multimode(a)

[1, 2, 3, 6]

In [23]:
a = np.random.randint(0, 10, (10, 10))
print(a)

[[8 4 1 2 8 6 5 6 0 5]
 [5 5 8 3 9 5 4 9 1 9]
 [5 4 7 4 2 4 8 8 6 4]
 [3 1 9 6 6 8 2 7 3 8]
 [7 3 3 4 4 1 1 9 8 0]
 [0 1 2 9 8 7 7 1 7 1]
 [1 7 3 2 0 6 6 7 9 8]
 [7 7 9 3 0 7 7 8 8 1]
 [9 0 4 9 9 8 5 4 8 3]
 [7 0 9 0 7 4 9 8 4 1]]


In [26]:
mr0 = scipy.stats.mode(a, axis=0)
print(mr0.mode)
print(mr0.count)

[7 0 9 2 0 4 5 8 8 1]
[3 2 3 2 2 2 2 3 3 3]


In [27]:
mr1 = scipy.stats.mode(a, axis=1)
print(mr1.mode)
print(mr1.count)

[5 5 4 3 1 1 6 7 9 0]
[2 3 4 2 2 3 2 4 3 2]
